- name: Install VSCode
  homebrew_cask: name=visual-studio-code state=present

- name: Install VSCode Extensions
  command: code --install-extension {{ extension }}
  loop_control:
    loop_var: extension
  loop: "{{ vscode_extensions }}"
