- name: Install VSCode
  homebrew_cask: name=visual-studio-code state=present

- name: Configure VSCode
  template: src=settings.json.j2 dest={{ editor_vscode_config_path }}

- name: Install VSCode Extensions
  command: code --install-extension {{ extension }}
  loop_control:
    loop_var: extension
  loop: "{{ editor_vscode_extensions }}"

- name: Tap Homebrew Fonts
  homebrew_tap: name=homebrew/cask-fonts

- name: Install Preferred Programming Font
  vars:
    cask_font_family: "{{ editor_font_family | replace(' ', '-') | lower }}"
  homebrew_cask: name=font-{{ editor_cask_font_family | default(cask_font_family) }}
