- name: Install ZSH
  homebrew: name=zsh

- name: Install Zpresto
  block:
    - git:
        repo: https://github.com/sorin-ionescu/prezto.git
        update: no
        dest: ~/.zprezto
        accept_hostkey: yes
    - stat: path=~/.zlogin
      register: zlogin
    - when: zlogin.stat.exists == false
      shell: ./prezto_postinstall.sh
      args:
        chdir: "{{ role_path }}/files"

- name: Install iTerm2
  homebrew_cask: name=iterm2

- name: Configure ZSH
  copy: src=.zshrc dest=~/.zshrc
